### ISSUE TITLE
Capture commit hash when benchmarking

### ISSUE THREAD

**Issue by ngupta23** [pycaret/benchmarks#12]
Since we can benchmark the unreleased version of pycaret, we need to capture the GitHub commit hash in the results. For example, the [results here](https://github.com/pycaret/benchmarks/blob/26597dd3da83a81f78289d64986c054194869459/data/evaluation.csv) point to 3.0.0rc6, but this is actually for the unreleased 3.0.0rc7

https://github.com/pycaret/benchmarks/blob/26597dd3da83a81f78289d64986c054194869459/requirements.txt#L3

**Comment by ngupta23** [comment]
Check with @Yard1 on how this can be accomplished.

**Comment by Yard1** [comment]
Try
```python
import re

try:
    from pip._internal.operations import freeze
except ImportError:
    from pip.operations import freeze

pkgs = " ".join(freeze.freeze())
match = re.search(r"-e git\+https://github\.com/pycaret/pycaret\.git@([^#]*)", pkgs)
assert match, "pycaret is not installed from git or installed at all"
pycaret_hash = match.group(1)
print(pycaret_hash)
```
